language: node_js
deploy:
  on:
    branch: master
  provider: heroku
  api_key:
    secure: OZ/QwgTATmjg6G0lzb7lHRJr0viJJQGGWcqFKInMcyfudLPdAL0J5xkFCfMyv7ajZQ050N/YuWx/aumPvWE4E2l9oxLV2CDUavVz71ewTrPm85df2DdqQcaRJ3kAwQVtHKwSS1o53AJe/eTVnUPeiSYGJ0Kw4Hki6f2DSLbD64pyPUJiSLUBRDQdvTFKOlYEOdWNn11flxbX+y/OyvaUvSDwkId/ZGxr9J1onQ4Adm/SzntS20wxvXHnpI/O8uo+Z0lCck8sSZ32bta89yBBQeXN1HsOOwZFzab/bAYLD4XZ72KC4kQgTVuofUFYCC/4Et5nvmgMDCOY1sdL73JQje6nscUFBR+btkOzroR729LhF7nIeNOZ7ZXMzAYPaTFhZEYA7lFnI7kZdOVlQGGPkUoEOx79cx4YYrXPYdIYvsaVisp5RsiGl6Mnq+LBINXNvcwt8kyH4OvXJla9AlBh0To4R2DxeRtyH4vAM7mz9zfzTC2tQwo7LKYPQtW+cPf4C1331Fz8OXQSeqRcLfhhXIxclC+yuDo7c5FDmGs6ERnd/v2iMtshzA/wU4tzqTnLj1pXuDafhyk0np5i8htYRp5UzGXheYQUAkLyfNrn/jAOJoDhyP0z7cO0P4aR3SxkcWAZMdRXh1nk0/tXHxvqbnFceAihTYfdZeNTH3BaMPM=
