# and export GOOGLE_PRIVATE_KEY='contentFromPrivateKey'
google:
  private_key_id: GOOGLE_KEY_ID
  decrypt_password: DECRYPT_PASSWORD
azure:
  microsoft_app_password: MICROSOFT_APP_PASSWORD
  microsoft_app_id: MICROSOFT_APP_ID
  direct_line_token: DIRECT_LINE_TOKEN
